version: "3"
volumes:
  storage:
services:
  go:
    links:
      - mysql
    build:
      context: "./"
    tty: true
    ports:
      - 8095:8081
    volumes:
      - ".:/go/src/app"
    depends_on:
      - mysql
  mysql:
    build:
      context: "mock/"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      #      - "storage:/var/lib/mysql"
      - "./mock/initdb/:/docker-entrypoint-initdb.d"